image: "registry.dolt.ch/iot/monitor/image:latest"
# Image with rust, gcc, asciidoctor, asciidoctor-pdf

#services:
#  - redis:latest
#  - postgres:latest

pages:
    script:
        - asciidoctor --version
        - mkdir public
        - cd specs && asciidoctor -v index.adoc -a data-uri && cd ..
        - cp specs/index.html public/
    artifacts:
        paths:
            - public

build:specs:
  script:
    - asciidoctor-pdf --version
    - cd specs && asciidoctor-pdf -v index.adoc && cd ..
  artifacts:
          paths:
                  - specs/readme.pdf

# Use cargo to test the project
test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo build --all --verbose --jobs 1 --release
  - cargo test --all --verbose --jobs 1 --release # Don't paralize to make errors more readable
